x-node: &nodebase
  build: .
  networks:
    - p2p
  volumes:
    - ./mem_pools:/app/mem_pools
  depends_on:
    node1:
      condition: service_healthy

services:
  miner:
    build: .
    container_name: node1
    ports:
      - "5000:5000"
    networks:
      - p2p
    environment:
      HOST: "node1"
    volumes:
      - /home/urielazar/Documents/Projects/blockchain/mem_pools:/app/mem_pools
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/chain" ]
      interval: 10s
      timeout: 5s
      retries: 3

  node:
    <<: *nodebase
    deploy:
      mode: replicated
      replicas: 3

networks:
  p2p:
    driver: bridge
