services:
  node1:
    image: blockchain:latest
    container_name: node1
    ports:
      - "5000:5000"
    networks:
      - p2p
    environment:
      HOST: "node1"
    volumes:
      - /home/urielazar/Documents/Projects/blockchain/mem_pools:/app/mem_pools
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/chain" ]
      interval: 10s
      timeout: 5s
      retries: 3

  node2:
    image: blockchain:latest
    container_name: node2
    ports:
      - "5001:5000"
    networks:
      - p2p
    environment:
      HOST: "node2"
    volumes:
      - ./mem_pools:/app/mem_pools
    depends_on:
      node1:
        condition: service_healthy

  node3:
    image: blockchain:latest
    container_name: node3
    ports:
      - "5002:5000"
    networks:
      - p2p
    environment:
      HOST: "node3"
    volumes:
      - ./mem_pools:/app/mem_pools
    depends_on:
      node1:
        condition: service_healthy

networks:
  p2p:
    driver: bridge
