x-node: &nodebase
  build: .
  networks:
    - p2p
  volumes:
    - ./mem_pools:/app/mem_pools


services:
  miner:
    <<: *nodebase
    ports:
      - "5000:5000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/chain" ]
      interval: 10s
      timeout: 5s
      retries: 3

  node:
    <<: *nodebase
    deploy:
      mode: replicated
      replicas: 3
    depends_on:
      miner:
        condition: service_healthy

networks:
  p2p:
    driver: bridge
